name: CI/CD BUILD-AND-TEST

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check if DOCKER_USERNAME secret is set
        run: |
          if [ -z "$DOCKER_USERNAME" ]; then
            echo "DOCKER_USERNAME secret is empty or not set"
            exit 1
          else
            echo "DOCKER_USERNAME secret is set"
          fi
